[package]
name = "create-azul-board"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "*"
itertools = "*"
rand = "*"
image = "*"
uuid = {version = "0.4", features = ["v4"]}
